insert into public.questions (id, category, emoji, prompt, option_a, option_b, leans) values
('q_pizza', 'comida', '🍕', '¿Pizza o hamburguesa?', 'Pizza', 'Hamburguesa', '{"comfort":0,"night":1}'::jsonb),
('q_breakfast', 'comida', '☕', '¿Desayuno grande o café y listo?', 'Desayuno grande', 'Café y listo', '{"comfort":0,"planner":1}'::jsonb),
('q_cook', 'comida', '🍳', '¿Cocinar o pedir?', 'Cocinar', 'Pedir', '{"planner":0,"spender":1}'::jsonb),
('q_beach', 'viajes', '🏖️', '¿Playa o montaña?', 'Playa', 'Montaña', '{"comfort":0,"adventure":1}'::jsonb),
('q_solo', 'viajes', '🎒', '¿Viajar solo o acompañado?', 'Solo', 'Acompañado', '{"adventure":0,"outgoing":1}'::jsonb),
('q_plan', 'viajes', '🗺️', '¿Itinerario cerrado o improvisar?', 'Itinerario', 'Improvisar', '{"planner":0,"adventure":1}'::jsonb),
('q_money', 'dinero', '💸', '¿Ahorrar o gastar?', 'Ahorrar', 'Gastar', '{"planner":0,"spender":1}'::jsonb),
('q_gift', 'dinero', '🎁', '¿Regalo útil o regalo sorpresa?', 'Útil', 'Sorpresa', '{"planner":0,"outgoing":1}'::jsonb),
('q_split', 'dinero', '💳', '¿Pagar a medias o invitar yo?', 'A medias', 'Invito yo', '{"planner":0,"spender":1}'::jsonb),
('q_night', 'planes', '🏠', '¿Salir o quedarse en casa?', 'Salir', 'Quedarme', '{"outgoing":0,"night":0,"comfort":1}'::jsonb),
('q_friday', 'planes', '📅', '¿Plan con tiempo o a última hora?', 'Con tiempo', 'A última hora', '{"planner":0,"night":1}'::jsonb),
('q_group', 'planes', '👥', '¿Grupo grande o grupo pequeño?', 'Grande', 'Pequeño', '{"outgoing":0,"comfort":1}'::jsonb),
('q_music', 'musica', '🎧', '¿Playlist o aleatorio?', 'Playlist', 'Aleatorio', '{"planner":0,"adventure":1}'::jsonb),
('q_live', 'musica', '🎤', '¿Concierto o auriculares?', 'Concierto', 'Auriculares', '{"outgoing":0,"comfort":1}'::jsonb),
('q_volume', 'musica', '🔊', '¿Volumen alto o bajo?', 'Alto', 'Bajo', '{"night":0,"comfort":1}'::jsonb),
('q_sport', 'deporte', '⚽', '¿Deporte de equipo o solo?', 'Equipo', 'Solo', '{"outgoing":0,"adventure":1}'::jsonb),
('q_gym', 'deporte', '🏃', '¿Gimnasio o aire libre?', 'Gimnasio', 'Aire libre', '{"planner":0,"adventure":1}'::jsonb),
('q_win', 'deporte', '🏅', '¿Competir o pasarlo bien?', 'Competir', 'Pasarlo bien', '{"outgoing":0,"comfort":1}'::jsonb),
('q_late', 'noche', '🌙', '¿Quedarte hasta tarde o irte pronto?', 'Hasta tarde', 'Pronto', '{"night":0,"planner":1}'::jsonb),
('q_toast', 'noche', '🥂', '¿Brindar o agua?', 'Brindar', 'Agua', '{"outgoing":0,"planner":1}'::jsonb),
('q_dance', 'noche', '💃', '¿Bailar o conversar?', 'Bailar', 'Conversar', '{"outgoing":0,"comfort":1}'::jsonb),
('q_home', 'casa', '🛋️', '¿Orden o caos creativo?', 'Orden', 'Caos creativo', '{"planner":0,"adventure":1}'::jsonb),
('q_pet', 'casa', '🐾', '¿Perro o gato?', 'Perro', 'Gato', '{"outgoing":0,"comfort":1}'::jsonb),
('q_host', 'casa', '🚪', '¿Recibir gente o casa en calma?', 'Recibir gente', 'Casa en calma', '{"outgoing":0,"comfort":1}'::jsonb),
('q_style', 'estilo', '🖤', '¿Todo negro o color?', 'Todo negro', 'Color', '{"night":0,"outgoing":1}'::jsonb),
('q_shop', 'estilo', '🛍️', '¿Marcas o de segunda?', 'Marcas', 'De segunda', '{"spender":0,"planner":1}'::jsonb),
('q_fit', 'estilo', '👟', '¿Arreglado o cómodo?', 'Arreglado', 'Cómodo', '{"planner":0,"comfort":1}'::jsonb),
('q_meet', 'gente', '🗣️', '¿Hablar con desconocidos o quedarte con los tuyos?', 'Desconocidos', 'Los míos', '{"outgoing":0,"comfort":1}'::jsonb),
('q_text', 'gente', '💬', '¿Audio o texto?', 'Audio', 'Texto', '{"outgoing":0,"planner":1}'::jsonb),
('q_secret', 'gente', '🤫', '¿Contarlo todo o guardártelo?', 'Contarlo', 'Guardármelo', '{"outgoing":0,"comfort":1}'::jsonb),
('q_morning', 'tiempo', '⏰', '¿Madrugar o dormir?', 'Madrugar', 'Dormir', '{"planner":0,"night":1}'::jsonb),
('q_weekend', 'tiempo', '📆', '¿Agenda llena o hueco vacío?', 'Agenda llena', 'Hueco vacío', '{"outgoing":0,"comfort":1}'::jsonb),
('q_rush', 'tiempo', '⏱️', '¿Con prisa o con margen?', 'Con prisa', 'Con margen', '{"night":0,"planner":1}'::jsonb),
('q_film', 'gustos', '🎬', '¿Cine o peli en casa?', 'Cine', 'En casa', '{"outgoing":0,"comfort":1}'::jsonb),
('q_book', 'gustos', '📚', '¿Libro o serie?', 'Libro', 'Serie', '{"comfort":0,"night":1}'::jsonb),
('q_season', 'gustos', '🌤️', '¿Verano o invierno?', 'Verano', 'Invierno', '{"outgoing":0,"comfort":1}'::jsonb),
('q_sweet', 'comida', '🍰', '¿Dulce o salado?', 'Dulce', 'Salado', '{"comfort":0,"planner":1}'::jsonb),
('q_spice', 'comida', '🌶️', '¿Picante o suave?', 'Picante', 'Suave', '{"adventure":0,"comfort":1}'::jsonb),
('q_city', 'viajes', '🏙️', '¿Ciudad o pueblo?', 'Ciudad', 'Pueblo', '{"outgoing":0,"comfort":1}'::jsonb),
('q_fly', 'viajes', '✈️', '¿Avión o tren?', 'Avión', 'Tren', '{"spender":0,"planner":1}'::jsonb),
('q_tip', 'dinero', '🪙', '¿Propina generosa o justa?', 'Generosa', 'Justa', '{"spender":0,"planner":1}'::jsonb),
('q_sale', 'dinero', '🏷️', '¿Esperar la rebaja o comprarlo ya?', 'Esperar', 'Ya', '{"planner":0,"spender":1}'::jsonb),
('q_surprise', 'planes', '🎁', '¿Plan sorpresa o plan contado?', 'Sorpresa', 'Contado', '{"adventure":0,"planner":1}'::jsonb),
('q_rain', 'planes', '🌧️', '¿Si llueve, cancelar o salir igual?', 'Cancelar', 'Salir igual', '{"comfort":0,"adventure":1}'::jsonb),
('q_lyrics', 'musica', '🎶', '¿Cantado o instrumental?', 'Cantado', 'Instrumental', '{"outgoing":0,"comfort":1}'::jsonb),
('q_ears', 'musica', '🎧', '¿Compartir auriculares o cada uno lo suyo?', 'Compartir', 'Cada uno', '{"outgoing":0,"comfort":1}'::jsonb),
('q_watch', 'deporte', '📺', '¿Ver el partido o jugarlo?', 'Verlo', 'Jugarlo', '{"comfort":0,"outgoing":1}'::jsonb),
('q_train', 'deporte', '🌅', '¿Entreno de mañana o de noche?', 'Mañana', 'Noche', '{"planner":0,"night":1}'::jsonb),
('q_after', 'noche', '🌃', '¿After o a casa?', 'After', 'A casa', '{"night":0,"comfort":1}'::jsonb),
('q_camera', 'noche', '📸', '¿Fotos de la noche o nada de cámara?', 'Fotos', 'Nada', '{"outgoing":0,"comfort":1}'::jsonb),
('q_plants', 'casa', '🪴', '¿Plantas o espacios vacíos?', 'Plantas', 'Vacío', '{"comfort":0,"planner":1}'::jsonb),
('q_sofa', 'casa', '🛋️', '¿Sofá compartido o cada uno en su sitio?', 'Compartido', 'Cada uno', '{"outgoing":0,"comfort":1}'::jsonb),
('q_scent', 'estilo', '🧴', '¿Perfume o nada?', 'Perfume', 'Nada', '{"outgoing":0,"comfort":1}'::jsonb),
('q_sun', 'estilo', '🕶️', '¿Gafas de sol o gorra?', 'Gafas', 'Gorra', '{"planner":0,"comfort":1}'::jsonb),
('q_call', 'gente', '📞', '¿Llamar o escribir?', 'Llamar', 'Escribir', '{"outgoing":0,"planner":1}'::jsonb),
('q_mute', 'gente', '🔕', '¿Grupo de chat activo o silenciado?', 'Activo', 'Silenciado', '{"outgoing":0,"comfort":1}'::jsonb),
('q_early', 'tiempo', '⌚', '¿Llegar pronto o en punto?', 'Pronto', 'En punto', '{"planner":0,"night":1}'::jsonb),
('q_nap', 'tiempo', '😴', '¿Siesta o seguir?', 'Siesta', 'Seguir', '{"comfort":0,"planner":1}'::jsonb),
('q_board', 'gustos', '🎲', '¿Videojuego o juego de mesa?', 'Videojuego', 'Mesa', '{"night":0,"outgoing":1}'::jsonb),
('q_quiet', 'gustos', '🎙️', '¿Podcast o silencio?', 'Podcast', 'Silencio', '{"outgoing":0,"comfort":1}'::jsonb);
